### ISSUE TITLE
Clarification on docs/vps_routing.md

### ISSUE THREAD

**Issue by hvddrift** [sam-brownlow/jellytin#7]
This part

Under Client IP Address Filtering set Is in = __VPS_IP__

what is an example of __VPS_IP__? 
The IP of the machine eg100.96.121.3 or
The IP of the DNS eg: 100.100.100.100
or the magic dns name?

**Comment by sam-6174** [comment]
The IP address is the one referenced [here](https://github.com/sam-6174/jellytin/blob/a7e19ebdb25e789ab0ba856c7b04d3a34568641c/README.md?plain=1#L29).

This is the static IP address of your VPS machine.  The filter you're creating is to limit the Cloudflare token usage to only being used from the VPS's IP address.  It's an added layer of security.
